rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - 2.2.2
  - jruby-19mode
  - rbx-2.2.10
services:
  - couchdb
gemfile:
  - active_support_4_0
  - active_support_4_1
  - active_support_4_2
before_script:
  - sudo sh -c 'echo "[native_query_servers]" >> /etc/couchdb/local.ini'
  - sudo sh -c 'echo "erlang = {couch_native_process, start_link, []}" >> /etc/couchdb/local.ini'
  - sudo /etc/init.d/couchdb restart
  - bundle
script: bundle exec rake
matrix:
  allow_failures:
    - rvm: jruby-19mode
