rvm:
  - 2.0.0
  - 2.1.2
  - 2.2.2
  - jruby-9.0.1.0
  - rbx-2.5.8
sudo: false
services:
  - couchdb
gemfile:
  - gemfiles/active_support_4_0
  - gemfiles/active_support_4_1
  - gemfiles/active_support_4_2
script: bundle exec rake
